### ISSUE TITLE
tutorials/formatting_code.md fails on second step

### ISSUE THREAD

**Issue by bttk** [google/startup-os#410]
I followed this link:

[![Open in Cloud Shell](http://gstatic.com/cloudssh/images/open-btn.svg)](https://console.cloud.google.com/cloudshell/open?git_repo=https://github.com/google/startup-os&page=shell&tutorial=tutorials/formatting-code.md)

In the second step I executed `bazel build //tools/formatter` and got this error:

```
$ bazel build //tools/formatter
INFO: Analysed target //tools/formatter:formatter (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /tmp/bazel/e0dde365cd6c83fcc35ecc8d725f7387/external/bazel_tools/tools/jdk/BUILD:197:1: SkylarkAction external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) java failed: error executing command external/embedded_jdk/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp ... (remaining 5 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
warning: could not find a JDK 8 bootclasspath in external/local_jdk, falling back to --release
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Option.process(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(Unknown Source)
        at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:141)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:76)
Target //tools/formatter:formatter failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.405s, Critical Path: 0.63s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 3 processes: 3 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by vmax** [comment]
@bttk thank you for finding the issue! would you mind checking whether it works at [`fix-gcs-tutorial`](https://github.com/google/startup-os/tree/fix-gcs-tutorial) branch?

You'll have to manually run the tutorial though. Here's how you can do it after following the link:
```
git checkout fix-gcs-tutorial
teachme tutorials/formatting-code.md
```

**Comment by bttk** [comment]
Works for me. I have run into some problems with the first step - for these I have added comments to 48d27e78712e9aa36429cb000cbafdd184603440
